export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE'

export const ADD_PRODUCT = 'ADD_PRODUCT'
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'
export const ADD_PRODUCT_FAILURE = 'ADD_PRODUCT_FAILURE'
export const TITLE_ERROR="TITLE_ERROR"
export const PROD_DESC="PROD_DESC"
export const ADD_TO_WISHLIST="ADD_TO_WISHLIST"

export const GET_PRODUCT = 'GET_PRODUCT'
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE'

export const DELETE_PRODUCT="DELETE_PRODUCT"
export const DELETE_PRODUCT_SUCCESS="DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_FAILURE="DELETE_PRODUCT_FAILURE"

export const SEARCH_PRODUCT="SEARCH_PRODUCT"
export const SET_TO_FALSE='SET_TO_FALSE'

